sudo: false
language: python
env:
  - DJANGO_VERSION="Django>=1.10,<1.11"
  - DJANGO_VERSION="Django>=1.11,<1.12"
  - DJANGO_VERSION="Django>=2.0,<2.1"
  - DJANGO_VERSION='https://github.com/django/django/archive/master.tar.gz'
python:
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - pip install -r requirements.freeze.txt
  - pip install -r requirements-test.txt
  - pip install -q $DJANGO_VERSION
before_script:
  - flake8
  - cd apps/aklub/
  - DJANGO_SETTINGS_MODULE="" django-admin compilemessages
  - cd ../..
script:
  - python manage.py --version
  - ./runtests.sh
after_script:
  - coveralls
addons:
  postgresql: "9.3"
matrix:
   exclude:
      - python: "3.6"
        env: DJANGO_VERSION="Django>=1.10,<1.11"
      - python: "3.4"
        env: DJANGO_VERSION='https://github.com/django/django/archive/master.tar.gz'
   allow_failures:
      - env: DJANGO_VERSION='https://github.com/django/django/archive/master.tar.gz'
